stryker4s {
  mutate = ["src/main/scala/de/htwg/se/machikoro/remake/**/*.scala"
  "!src/main/scala/de/htwg/se/machikoro/remake/controller/mementoPatern/*.scala"]
  test-filter = ["*Spec"]
  reporters = ["console", "html"]
  dialect = scala3
  concurrency = 1
}