    name: Scala CI

    on:
    push:
    branches: [ master,  ]
    pull_request:
    branches: [ master ]

    jobs:
    test:
    runs-on: ubuntu-latest

    steps:
      
        name: Checkout Repository
          uses: actions/checkout@v4

      
        name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '17'

      
        name: Cache SBT Dependencies
          uses: actions/cache@v4
          with:
            path: |~/.ivy2/cache~/.sbt~/.coursier/cache
            key: ${{ runner.os }}-sbt-${{ hashFiles('*/.sbt') }}
            restore-keys: |${{ runner.os }}-sbt-

      
        name: Compile
          run: sbt compile

      
        name: Run Tests
          run: sbt test

      
        name: Generate Coverage Report
          run: sbt clean coverage test coverageReport

      
        name: Upload Coverage to Coveralls
          env:
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          run: sbt coveralls

      
        name: Run Mutation Tests
          run: sbt stryker4s

﻿
